# Generated by Django 3.2.5 on 2021-07-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Количество/объем'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
