# Generated by Django 3.2.5 on 2021-07-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210716_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
